---
- name: clean up created incidents
  hosts: localhost
  connection: local
  become: false
  vars:
    demo_username:

  tasks:

  - name: find incidents created by {{ demo_username }}
    servicenow.itsm.incident_info:
      query:
        - description: LIKE {{ demo_username }}
    register: userIncidents

  - name: dump incidents
    debug:
      var: userIncidents