---
- name: clean up created incidents
  hosts: localhost
  connection: local
  become: false
  vars:
    demo_username:

  tasks:

  - name: find incidents created by {{ demo_username }}
    servicenow.itsm.incident_info:
      query:
        - sys_created_by: LIKE {{ demo_username }}
    register: userIncidents

  - name: find problems created by {{ demo_username }}
    servicenow.itsm.problem_info:
      query:
        - sys_created_by: LIKE {{ demo_username }}
    register: userProblems

  # - name: find problem tasks created by {{ demo_username }}
  #   servicenow.itsm.problem_task_info:
  #     query:
  #       - sys_created_by: LIKE {{ demo_username }}
  #   register: userProblemTasks

  - name: find change requests created by {{ demo_username }}
    servicenow.itsm.change_request_info:
      query:
        - sys_created_by: LIKE {{ demo_username }}
    register: userChangeRequests

  # - name: find change request tasks created by {{ demo_username }}
  #   servicenow.itsm.change_request_task_info:
  #     query:
  #       - sys_created_by: LIKE {{ demo_username }}
  #   register: userChangeRequestTasks

  - name: find configuration item created by {{ demo_username }}
    servicenow.itsm.configuration_item_info:
      query:
        - sys_created_by: LIKE {{ demo_username }}
    register: userConfigItems

  - name: dump user created records
    debug: 
      var: "{{ item }}"
    loop:
      - "{{ userIncidents }}"
      - "{{ userProblems }}"
      # - "{{ userProblemTasks }}"
      - "{{ userChangeRequests }}"
      # - "{{ userChangeRequestTasks }}"
      - "{{ userConfigItems }}"
