---
- name: find all users with last name Demouser
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    username: "{{ lookup('env', 'SN_USERNAME') }}"
    password: "{{ lookup('env', 'SN_PASSWORD') }}"
    instance: "{{ lookup('env', 'SN_HOST') }}"
    user_query: last_name=Demouser

  tasks:

  - name: find all users with last name Demouser
    uri:
      url: "{{ instance }}/api/now/table/sys_user?sysparm_query=last_name={{ user_query }}"
      method: GET
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: true
      headers:
        Content-Type: application/json
      status_code: 200
    register: users

  - name: dump users
    debug:
      var: item.user_name
    with_items: "{{ users.json.result }}"