---
- name: find records by tag
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    username: "{{ lookup('env', 'SN_USERNAME') }}"
    password: "{{ lookup('env', 'SN_PASSWORD') }}"
    instance: "{{ lookup('env', 'SN_HOST') }}"

  tasks:

    - name: find incidents by query
      uri:
        url: "{{ instance }}/api/now/table/incident?sysparm_query=sys_tags.2b7609eb1bd2c110b76a0d0fdc4bcb70=2b7609eb1bd2c110b76a0d0fdc4bcb70&active=true"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: true
        headers:
          Content-Type: application/json
        status_code: 200
      register: incidents

    - name: find problems by query
      uri:
        url: "{{ instance }}/api/now/table/problem?sysparm_query=sys_tags.2b7609eb1bd2c110b76a0d0fdc4bcb70=2b7609eb1bd2c110b76a0d0fdc4bcb70&active=true"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: true
        headers:
          Content-Type: application/json
        status_code: 200
      register: problems

    - name: find change requests by query
      uri:
        url: "{{ instance }}/api/now/table/change_request?sysparm_query=sys_tags.2b7609eb1bd2c110b76a0d0fdc4bcb70=2b7609eb1bd2c110b76a0d0fdc4bcb70&active=true"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: true
        headers:
          Content-Type: application/json
        status_code: 200
      register: changes

    - set_fact:
        incident_list: []
        problem_list: []
        change_list: []

    - name: query incident number and creation time 
      set_fact:
        incident_list: '{{ incident_list + [{"number": item.number, "opened_at": item.opened_at}] }}'
      loop: "{{ incidents.json.result }}"
      when: incidents

    - name: query problem number and creation time 
      set_fact:
        problem_list: '{{ problem_list + [{"number": item.number, "opened_at": item.opened_at}] }}'
      loop: "{{ problems.json.result }}"
      when: problems

    - name: query change number and creation time 
      set_fact:
        change_list: '{{ change_list + [{"number": item.number, "opened_at": item.opened_at}] }}'
      loop: "{{ changes.json.result }}"
      when: changes

    - name: clean up records
      include_tasks: close-records.yml