---
- name: query list of users from SNOW instance
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    username: "{{ lookup('env', 'SN_USERNAME') }}"
    password: "{{ lookup('env', 'SN_PASSWORD') }}"
    instance: "{{ lookup('env', 'SN_HOST') }}"
    user_query: last_name=Demouser

  tasks:
  - name: find users by query
    uri:
      url: "{{ instance }}/api/now/table/sys_user?sysparm_query={{ user_query }}"
      method: GET
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: true
      headers:
        Content-Type: application/json
      status_code: 200
    register: user_list

  - name: set_fact
    set_fact:
      users: "{{ user_list | json_query('json.result[*].user_name') }}"

  - name: print users
    debug:
      var: users

  - name: find and remove records
    include_tasks: cleanup-records.yml