---
- name: find records by tag
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    username: "{{ lookup('env', 'SN_USERNAME') }}"
    password: "{{ lookup('env', 'SN_PASSWORD') }}"
    instance: "{{ lookup('env', 'SN_HOST') }}"

  tasks:
    - name: Create a problem
      servicenow.itsm.problem:
        state: new
        short_description: Issue with the network printer
        description: Since this morning, all printer jobs are stuck.
        impact: medium
        urgency: low
      register: problem

    - debug:
        var: problem

    - name: assign the problem
      servicenow.itsm.problem:
        number: "{{ problem.record.number }}"
        state: assess
        assigned_to: admin

    - name: close problems from list
      servicenow.itsm.problem:
        state: "closed"
        fix_notes: "Closed with ansible servicenow.itsm" 
        number: "{{ problem.record.number }}"