---
- name: Get information from ServiceNow record
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print record information
      when: event.number is defined
      ansible.builtin.debug:
        msg: "Record: {{ event.number }}, Description: {{ event.short_description }}"

    - name: Print record information
      when: event.number is undefined
      ansible.builtin.debug:
        msg: "Record: {{ event.sys_id }}, Description: {{ event.name }}"
