---
- name: Get information from ServiceNow record
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print record information
      debug:
        msg: "Record: {{ event.number }}, Description: {{ event.short_description }}"
      when: event.number is defined

    - name: Print record information
      debug:
        msg: "Record: {{ event.sys_id }}, Description: {{ event.name }}"
      when: event.number is undefined